create table public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  enquiry text not null,
  owner text not null default 'Unassigned' check (owner in ('Unassigned', 'Alex', 'Sarah', 'John')),
  status text not null default 'New' check (status in ('New', 'Contacted', 'Qualified', 'Closed')),
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.leads enable row level security;

create policy "Allow public lead reads" on public.leads for select to anon using (true);
create policy "Allow public lead inserts" on public.leads for insert to anon with check (true);
create policy "Allow public lead updates" on public.leads for update to anon using (true) with check (true);
create policy "Allow public lead deletes" on public.leads for delete to anon using (true);