create table public.leads (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  phone text,
  enquiry text not null,
  owner text not null default 'Unassigned' check (owner in ('Unassigned', 'Alex', 'Sarah', 'John')),
  status text not null default 'New' check (status in ('New', 'Contacted', 'Qualified', 'Closed')),
  created_at timestamptz not null default timezone('utc', now())
);

alter table public.leads enable row level security;

drop policy if exists "Allow public lead reads" on public.leads;
drop policy if exists "Allow public lead inserts" on public.leads;
drop policy if exists "Allow public lead updates" on public.leads;
drop policy if exists "Allow public lead deletes" on public.leads;
drop policy if exists "Allow authenticated lead reads" on public.leads;
drop policy if exists "Allow authenticated lead inserts" on public.leads;
drop policy if exists "Allow authenticated lead updates" on public.leads;
drop policy if exists "Allow authenticated lead deletes" on public.leads;

create policy "Allow authenticated lead reads" on public.leads for select to authenticated using (true);
create policy "Allow authenticated lead inserts" on public.leads for insert to authenticated with check (true);
create policy "Allow authenticated lead updates" on public.leads for update to authenticated using (true) with check (true);
create policy "Allow authenticated lead deletes" on public.leads for delete to authenticated using (true);